### ISSUE TITLE
izhihu脚本及插件无法在chrome dev 48.0.2540.0（64bit）中使用

### ISSUE THREAD

**Issue by T6Zksor** [unogz/izhihu#58]
之前使用的是chrome 46 stable，可以正常使用。
更换了chrome 48 dev版本后，出现：
一、脚本在tampermonkey能够正常提示已加载，但知乎页面无变化，知乎网页“设置”中也无显示“izhihu”选项。
二、更换为izhihu的chrome插件后，能够显示出“izhihu”选项，但选项选框无显示，且页面实际没有变化。
三、其它脚本在tampermonkey中能够正常使用。其它插件在chrome中能够正常使用。

**Comment by unogz** [comment]
Fixed by 2.13
