### ISSUE TITLE
图标仍然失效

### ISSUE THREAD

**Issue by yfdyh000** [unogz/izhihu#61]
https://github.com/unogz/izhihu/blob/7620c570eaf0ad94eca09dd4c72523c80e826643/src/meta.js#L22

**Comment by unogz** [comment]
是的，云主机欠费多日了 :P

**Comment by yfdyh000** [comment]
换个地址不好吗。放在Github也行吧。

**Comment by unogz** [comment]
是的，尽快解决它

**Comment by unogz** [comment]
已改用 github raw content
