### ISSUE TITLE
“快速收藏”在知乎启用HTTPS之后并没有什么卵用

### ISSUE THREAD

**Issue by xmcp** [unogz/izhihu#63]
当我hover收藏按钮时，并没有列出我的收藏夹，反而，错误出现了：

`Mixed Content: The page at 'https://www.zhihu.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.zhihu.com/collections/json?answer_id=24624358'. This request has been blocked; the content must be served over HTTPS.`

修复方法：把http换成https。

**Comment by unogz** [comment]
已修复
