### ISSUE TITLE
快速屏蔽功能不能在https下使用

### ISSUE THREAD

**Issue by zcyzcy88** [unogz/izhihu#66]
```
Mixed Content: The page at 'https://www.zhihu.com/settings/filter' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.zhihu.com/settings/unblockuser'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by unogz** [comment]
什么版本？

https://www.zhihu.com/settings/filter 应该是「https://www.zhihu.com/settings/filter」功能涉及的页面，最新版也已对 https 作了适配

**Comment by zcyzcy88** [comment]
![](https://cloud.githubusercontent.com/assets/15178410/11926339/d9cc98c4-a7fe-11e5-80a5-79983a9d1188.png)
这里（啊，标题应该成为快速解除屏蔽）

**Comment by unogz** [comment]
试试最新版呢？我记得已经高于 2.13.1 了

Sent from Outlook Mobile

On Mon, Dec 21, 2015 at 12:21 AM -0800, "zcyzcy88" notifications@github.com wrote:

这里（啊，标题应该成为快速解除屏蔽）
