### ISSUE TITLE
火狐57不能使用.

### ISSUE THREAD

**Issue by ghost** [unogz/izhihu#74]
火狐浏览器升级到57才发现这个刷知乎神器。
想要的，比如左边生成一个回答问题的人的标签页这些功能简直太喜欢了。
......然而没用过，且当跳转到插件安装地方时候显示，不适合当前版本.
想问这个还有没有人在维护，或者，我该怎么做才能使用它？
谢谢～

**Comment by unogz** [comment]
抱歉，事实上已处于停止维护状态。
